# Generated by Django 4.2.13 on 2024-05-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_subscriptiondata_ending_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiondata',
            name='id',
        ),
        migrations.AlterField(
            model_name='subscriptiondata',
            name='ID_sub',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
