# Generated by Django 4.2 on 2024-06-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MostSuccessfuldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_prod', models.CharField(max_length=200)),
                ('prod_desc', models.CharField(max_length=500)),
                ('revenue', models.FloatField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptiondata',
            fields=[
                ('ID_sub', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('ID_prod', models.CharField(max_length=200)),
                ('prod_desc', models.CharField(max_length=500)),
                ('price', models.FloatField()),
            ],
        ),
    ]
