# Generated by Django 4.2.13 on 2024-05-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiondata',
            name='ending_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiondata',
            name='starting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
