# Generated by Django 4.2.13 on 2024-05-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscriptiondata_ending_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiondata',
            name='ending_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondata',
            name='starting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
